version: '3.9'

services:
  db:
    image: mysql:8.4
    container_name: smartendance-db-v1
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - ./web/.mysqlenv
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD="no"
      - MYSQL_ALLOW_EMPTY_PASSWORD="no"
    volumes:
      - smartendance-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      retries: 10
      start_period: 30s
  
  web:
    build: ./web
    container_name: smartendance-app-v1
    ports:
      - 8080:5555
    env_file:
      - ./web/.flaskenv
    links:
      - db:mysqlctr
    depends_on:
      db:
        condition: service_healthy

volumes:
  smartendance-db:
