version: '3.9'

services:
  web:
    build: ./web
    container_name: smartendance-app-v1
    ports:
      - "8080:5555"
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: smartendance-db-v1
    restart: unless-stopped
    ports:
      - "3306:3306"
    env_file:
      - ./web/.flaskenv
    command: ["mysqld", "--mysql-native-password=ON"]
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: false
      MYSQL_RANDOM_ROOT_PASSWORD: false
    volumes:
      - smartendance-db:/var/lib/mysql

volumes:
  smartendance-db:
